### ISSUE TITLE
What is your selling point comparing to doctrine ?

### ISSUE THREAD

**Issue by lud** [opis/database#43]
Hello, 

I'm gathering informations on available DB tools for PHP. I know Doctrine is like a go-to for most programmers. What are the advantages of using this package ?

Thank you ?

**Comment by msarca** [comment]
Hello and thanks for your interest in *Opis Database*. Sorry for the late answer but since this wasn't a technical issue or bug, I've postponed a response. Below are some key features of the library. We do not claim that their are unique to our package, but we do provide them.

**Expressive query builder**
The library is shipped with an expressive query builder that allows developers to write complex queries without sacrificing code's comprehensibility. This is extremely important, especially for teams that are dealing with projects that requires maintenance over long periods of time, since there is a high probability that the team's structure will not be the same during the project's life.

**Built-in security**
The library's built-in security mechanism protect web applications against SQL injection and help developers stay focused on providing new features for their web apps instead of constantly worrying that their queries might be vulnerable.

**Easy to learn**
This is a not only a consequence of the expressive query builder and built-in security described above, but also something that we have deliberately designed for all our packages. If our junior developers/collaborators have difficulties in understanding some concepts, we go back to the drawing board and redesign our software until they can easily grasp it.

**Business friendly**
Being an open source company we take great care of our software and we make sure that we will not introduce breaking changes during the lifecycle of a major release. That's why we strictly adhere to semantic versioning and ensure forward compatibility.

**Comment by lud** [comment]
> Hello and thanks for your interest in Opis Database. Sorry for the late answer but since this wasn't a technical issue or bug, I've postponed a response. 

Of course, no problem :)

Thank you very much for your anwser, I will look further into this points.
