### ISSUE TITLE
psr/log support

### ISSUE THREAD

**Issue by GonistLelatel** [opis/database#61]
Please add the **psr/log ~1.0** interface support

like **Psr\Log\LoggerAwareInterface**
OR
like **Psr\Log\LoggerAwareTrait**

package https://packagist.org/packages/psr/log

`composer require psr/log ~1.0`

**Comment by sorinsarca** [comment]
In practice, this isn't a good idea because there are a lot of use cases. We cannot just send all queries to the logger.

1. what log level should we use?

`LoggerInterface` suggests to use `info`, but for some apps/websites a query that takes 3 seconds to complete can be viewed as a `warning`.

2. what sql statements we want to log?

One may need to log only `SELECT` queries, others only `DELETE`s or a combination of sql statements. 

3. why to log all?

Some people just want to log a `notice` if the total time for all queries is greater than 2 seconds.
Or maybe they want to filter and group the queries, for example:
- if total time of all `SELECT`s > 3 seconds then `info`
- `notice` for every `DELETE`
- `warning` for `ALTER TABLE`, `DROP TABLE`, etc.


As you can see, the best option is to handle the logging the way your app/project needs it.

Adding psr/log will not add something valuable to this library. A simple logging can be done in 5 lines of code.
```php
use Psr\Log\LoggerInterface;
use Opis\Database\Connection;

function logSqlQueries(Connection $connection, LoggerInterface $logger) {
   foreach ($connection->getLog() as $item) {
        // here you can filter and choose the log level
        $logger->info($item['query'], ['time' => $item['time']]);
   }
}
```

If there is something I missed please let me know.

**Comment by GonistLelatel** [comment]
So, its not simple. You may think about it some time or days. How to resolve the problem of the psr/log integration.

**Comment by sorinsarca** [comment]
> So, its not simple. You may think about it some time or days. How to resolve the problem of the psr/log integration.

It is simple: there is no problem to solve.

However, you can always extend the library with a few lines of code to add the logger.

```php
<?php

use Opis\Database\Connection;
use Psr\Log\{
    LoggerAwareInterface,
    LoggerAwareTrait
};

class ConnectionWithLogger extends Connection implements LoggerAwareInterface
{
    use LoggerAwareTrait;

    /**
     * @inheritDoc
     */
    protected function execute(array $prepared)
    {
        $ret = parent::execute($prepared);

        if ($this->logQueries && $this->logger) {
            $last = end($this->log);
            $this->logger->info($last['query'], [
                'time' => $last['time'],
            ]);
        }

        return $ret;
    }
}
```

And use it

```php
$conn = new ConnectionWithLogger(...);
$conn->setLogger(...);

$db = new \Opis\Database\Database($conn);
...
```
