### ISSUE TITLE
Get full raw SQL in 4.* before execution 

### ISSUE THREAD

**Issue by nguereza-tony** [opis/database#81]
Hello thank you again for this great library 
In some situations (debugging, etc.) we want to know the full raw SQL query, so how to get it in the library version 4.* ?
Thank

**Comment by msarca** [comment]
You can't do this because all queries are built at specific times, eg. when you call the `select` method. The only thing you can do is to log your queries. You can also take a look at our `Opis\Database\Test\Connection` [class](https://github.com/opis/database/blob/master/tests/Connection.php). We use that class to obtain the generated SQL queries without executing the SQL command.
